name: Windows Build

on: [push, pull_request]

env:
  MSVC_VERSION: 2019
  QT_VERSION: 5.15.2

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download Qt
      working-directory: ${{runner.workspace}}
      shell: pwsh
      run: |
        $url = "https://vgcci.blob.core.windows.net/vgc-ci"
        $filename = "qt-${env:QT_VERSION}-msvc${env:MSVC_VERSION}_64.zip"
        C:/msys64/usr/bin/wget.exe --progress=dot:giga "$url/$filename"
        unzip $filename
