name: Windows Build

on: [push, pull_request]

env:
  MSVC_VERSION: 2019
  QT_VERSION: 5.15.2

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Download Qt
      working-directory: ${{runner.workspace}}
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri https://www.vgc.io/releases/qt/DownloadTest.zip
        unzip https://www.vgc.io/releases/qt/DownloadTest.zip -d ${{runner.workspace}}
